<?php

namespace App\Models;


use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Facades\Storage;

class Product extends Model
{
    use HasFactory;


    protected $fillable = [
        'name',
        'description',
        'price',
        'image'
    ];
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::deleting(function (Product $product) {
            Storage::delete($product->getRawOriginal('image'));
        }); //good
    }

    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }
}
